apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: gow
spec:
  selector:
    app: springboot-app  # This matches the app label in the deployment
  ports:
    - protocol: TCP
      port: 80  # External port that users will access
      targetPort: 8080  # Port your Spring Boot app is running on inside the container
  type: LoadBalancer  # You can change this to ClusterIP or NodePort depending on your use case
